In [2]:
pip install sqlalchemy pymysql

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-py3-none-any.whl.metadata (9.5 kB)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.4.0-cp314-cp314-macosx_11_0_universal2.whl.metadata (3.7 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.49-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 10.2 MB/s  0:00:00 eta 0:00:01
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Downloading greenlet-3.4.0-cp314-cp314-macosx_11_0_universal2.whl (286 kB)
Installing collected packages: pymysql, greenlet, sqlalchemy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [sqlalchemy]3 [sqlalchemy]
Successfully installed greenlet-3.4.0 pymysql-1.1.2 sqlalchemy-2.0.49
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
from getpass import getpass
from sqlalchemy import create_engine

password = getpass("Enter your MySQL password: ")

connection_string = f"mysql+pymysql://root:{password}@localhost:3306/sakila"
engine = create_engine(connection_string)

In [3]:
query = """
SELECT *
FROM rental
LIMIT 5;
"""

test_df = pd.read_sql(query, engine)
test_df

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53

In [4]:
def rentals_month(engine, month, year):
    query = f"""
    SELECT *
    FROM rental
    WHERE MONTH(rental_date) = {month}
      AND YEAR(rental_date) = {year};
    """
    
    return pd.read_sql(query, engine)

In [5]:
may_2005 = rentals_month(engine, 5, 2005)
may_2005.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53

In [6]:
def rental_count_month(df, month, year):
    # count rentals per customer
    result = df.groupby("customer_id")["rental_id"].count().reset_index()
    
    # rename column dynamically
    col_name = f"rentals_{month:02d}_{year}"
    result = result.rename(columns={"rental_id": col_name})
    
    return result

In [7]:
may_counts = rental_count_month(may_2005, 5, 2005)
may_counts.head()

   customer_id  rentals_05_2005
0            1                2
1            2                1
2            3                2
3            5                3
4            6                3

In [8]:
def compare_rentals(df1, df2):
    # merge both monthly rental count tables
    result = pd.merge(df1, df2, on="customer_id", how="outer")
    
    # replace missing values with 0
    result = result.fillna(0)
    
    # get the two rental count column names
    rental_cols = [col for col in result.columns if col.startswith("rentals_")]
    
    # calculate difference between second month and first month
    result["difference"] = result[rental_cols[1]] - result[rental_cols[0]]
    
    return result

In [9]:
june_2005 = rentals_month(engine, 6, 2005)
june_counts = rental_count_month(june_2005, 6, 2005)

comparison = compare_rentals(may_counts, june_counts)
comparison.head()

   customer_id  rentals_05_2005  rentals_06_2005  difference
0            1              2.0              7.0         5.0
1            2              1.0              1.0         0.0
2            3              2.0              4.0         2.0
3            4              0.0              6.0         6.0
4            5              3.0              5.0         2.0